"""empty message

Revision ID: a5770519e694
Revises: 
Create Date: 2024-12-09 16:57:16.430878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5770519e694'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('register',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=500), nullable=False),
    sa.Column('password', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('register', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_register_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_register_username'), ['username'], unique=False)

    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eventTitle', sa.String(length=100), nullable=False),
    sa.Column('eventDate', sa.Date(), nullable=False),
    sa.Column('eventPlace', sa.String(length=250), nullable=False),
    sa.Column('eventCategory', sa.String(length=50), nullable=False),
    sa.Column('eventDescription', sa.String(length=1000), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['register.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_eventTitle'), ['eventTitle'], unique=False)

    op.create_table('rsvp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['register.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('upvotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['register.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('upvotes')
    op.drop_table('rsvp')
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_eventTitle'))

    op.drop_table('event')
    with op.batch_alter_table('register', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_register_username'))
        batch_op.drop_index(batch_op.f('ix_register_email'))

    op.drop_table('register')
    # ### end Alembic commands ###
